# Generated by Django 3.0.3 on 2020-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(default=' ', max_length=256, unique=True)),
                ('image_url', models.CharField(max_length=1000)),
                ('category', models.CharField(default=' ', max_length=20)),
                ('source', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
