# Generated by Django 3.0.3 on 2020-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200414_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
